(() => {
'use strict';
const $=s=>document.querySelector(s), canvas=$('#atlas'),ctx=canvas.getContext('2d'),mini=$('#minimap'),mctx=mini.getContext('2d');
const topics=window.ATLAS_CONTENT.topics, nested=window.NESTED_CONTENT, views=Object.fromEntries(nested.views.map(v=>[v.id,v]));
const palette={request:'#66d3e7',kv:'#e8b76b',control:'#b3a9ee',gpu:'#94c7d9',node:'#67b9b6',cloud:'#608db2',cache:'#d9ac67',scheduler:'#aca4e2',service:'#a0bdcf',failed:'#ef967b'};
const nodes=[],byId=new Map(),edges=[];let selected,hovered=null,W=1,H=1,dpr=1,cam={x:10000,y:6500,s:.05},baseScale=.05,animation=null,drawQueued=false,tourIndex=0,traceIndex=-1,tourActive=false,pointer=null,pointers=new Map(),pinch=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const root={id:'fleet',title:"Flota en la nube",subtitle:"Una solicitud, muchos dominios de fallo",x:0,y:0,w:20000,h:13200,parent:null,children:[],depth:0,kind:'root',topic:'cell_a'};nodes.push(root);byId.set(root.id,root);
function add(parent,id,title,x,y,w,h,opts={}){const n={id:parent.id+'/'+id,title,x:parent.x+x*parent.w,y:parent.y+y*parent.h,w:w*parent.w,h:h*parent.h,parent,children:[],depth:parent.depth+1,kind:'component',subtitle:'',...opts};parent.children.push(n);nodes.push(n);byId.set(n.id,n);return n;}
function edge(a,b,type='request',label='',parent=a.parent){edges.push({a,b,type,label,parent});}
function notes(title,summary,mechanism,tradeoff='',failure='',observe='',sources=[]){return {title,summary,mechanism,tradeoff,failure,observe,sources};}
function decorateLeaf(n,c,view){n.copy=notes(c.label,c.subtitle,c.inspector,view.note,'','',(c.sources||[]).map(s=>nested.sources[s]).filter(Boolean));}
function populate(n,viewId){const v=views[viewId];n.viewId=viewId;n.copy=notes(n.title,v.summary,v.note,'','','', [...new Set(v.children.flatMap(c=>c.sources||[]))].map(s=>nested.sources[s]).filter(Boolean));const local={};
 for(const c of v.children){const y=.13+c.y*.82,h=c.h*.82;const child=add(n,c.id,c.label,c.x,y,c.w,h,{kind:c.childView==='gpu'?'gpu-array':c.id.includes('hbm')?'cache':viewId==='scheduler'?'scheduler':'component',subtitle:c.subtitle});local[c.id]=child;decorateLeaf(child,c,v);
  if(viewId==='node'&&c.id==='gpus'){for(let i=0;i<8;i++){const gpu=add(child,'gpu-'+i,'GPU '+i,.035+(i%2)*.485,.14+Math.floor(i/2)*.21,.445,.185,{kind:'gpu',subtitle:"Rango TP "+i,topic:'hbm'});populate(gpu,'gpu');}}
  else if(c.childView)populate(child,c.childView);
  if(viewId==='gpu'&&c.id==='hbm'){add(child,'weights',"Pesos del modelo",.10,.19,.80,.25,{kind:'component',topic:'precision',subtitle:"Fragmento residente de parámetros"});const kv=add(child,'kv',"Páginas KV",.10,.52,.80,.30,{kind:'cache',topic:'kvpages',subtitle:"Estado de atención por rango"});populatePages(kv);}
  if(viewId==='kv'&&c.id==='hbm_pages')populatePages(child);
  if(viewId==='node'&&c.id==='cpu'){const a=add(child,'tokens',"Tokenización",.08,.27,.37,.25,{topic:'cpu'}),b=add(child,'metadata',"Metadatos del lote",.55,.27,.37,.25,{topic:'scheduler'}),d=add(child,'launch',"Envío de grafos",.25,.65,.50,.24,{topic:'graphs'});edge(a,b,'control','',child);edge(b,d,'control','',child);}
 }
 for(const e of v.edges){const type=e.type==='tensor'||e.type==='collective'||(viewId==='kv'&&e.type==='optional')?(viewId==='kv'?'kv':'request'):'control';edge(local[e.from],local[e.to],type,(e.type==='optional'?"Opcional: ":'')+e.label,n);}
}
function populatePages(parent){for(let i=0;i<12;i++)add(parent,'page-'+i,"Bloque "+i,.08+(i%3)*.3,.17+Math.floor(i/3)*.19,.24,.13,{kind:'page',topic:'kvpages',subtitle:i<3?"Prefijo compartido · 2 referencias":"Secuencia privada · 1 referencia",shared:i<3});}
function service(parent,id,title,x,y,w,h,topic,children){const n=add(parent,id,title,x,y,w,h,{kind:'service',topic});if(children){let previous;children.forEach((name,i)=>{const ch=add(n,'part-'+i,name,.08+(i%2)*.47,.25+Math.floor(i/2)*.32,.37,.22,{topic,kind:'component'});if(previous)edge(previous,ch,'control','',n);previous=ch;});}return n;}
const clients=service(root,'clients',"Clientes",.02,.045,.085,.085,'client',["Contrato de solicitud","Consumidor del flujo"]);
const edgeService=service(root,'edge',"Borde global",.155,.045,.105,.10,'edge',['TLS / WAF',"Autenticación","Enrutamiento regional","Proxy de flujos"]);
const admission=service(root,'admission',"Admisión / cuotas",.31,.045,.115,.10,'admission',["Presupuestos por cliente","Control de plazos","Estimaciones de tokens","Colas acotadas"]);
const router=service(root,'router',"Enrutador de flota",.485,.055,.12,.105,'router',["Compatibilidad del modelo","Afinidad KV","Estimaciones de carga","Destinos listos"]);
const artifacts=service(root,'artifacts',"Artefactos del modelo",.69,.055,.12,.11,'models',["Fragmentos de pesos","Tokenizador / escalas","Versiones / sumas de verificación","Preparación regional"]);
const control=service(root,'control',"Plano de control",.015,.275,.09,.11,'control',["Ubicación de cargas","Despliegues de modelos","Escalado automático","Descubrimiento"]);
const redis=service(root,'redis',"Redis / metadatos",.015,.48,.09,.11,'redis',["Concesiones de cuota","Pistas de enrutamiento","Caché de aplicación","Política de fallos"]);
const database=service(root,'database',"Base de datos persistente",.015,.69,.09,.11,'database',["Autoridad por cliente","Registro de consumo","Configuración versionada","Política de recuperación"]);
const region=add(root,'region',"Región principal",.135,.235,.655,.72,{kind:'cloud',topic:'fleet-regions',subtitle:"3 zonas · células de inferencia independientes"});
const standby=add(root,'standby',"Región de recuperación",.835,.34,.15,.52,{kind:'cloud',topic:'fleet-regions',subtitle:"Preparación y recuperación de datos independientes"});
const monitor=service(root,'observability',"Observabilidad",.835,.075,.14,.15,'telemetry',["TTFT + pausas entre tokens","Flujos completos","Capacidad por zona","Trazas + estado de GPU"]);
edge(clients,edgeService,'request',"API de transmisión",root);edge(edgeService,admission,'request',"Solicitud autenticada",root);edge(admission,router,'request',"Trabajo admitido",root);edge(admission,redis,'control',"Presupuestos / degradación acotada",root);edge(redis,database,'control',"Autoridad persistente",root);edge(artifacts,control,'control',"Versiones de modelo fijadas",root);edge(control,region,'control',"Ubicación / preparación",root);edge(router,standby,'control',"Política de recuperación ante desastres",root);edge(region,monitor,'control',"Telemetría de SLO y capacidad",root);
const clusterRefs=[];
function cluster(zone,label,id){const c=add(zone,id,label,.055,.12,.89,.83,{kind:'cluster',topic:'cell_a',subtitle:"2 réplicas de prellenado + 4 de decodificación · TP8 / PP1"});const sched=add(c,'scheduler',"Planificadores de réplica",.035,.23,.205,.28,{kind:'scheduler',topic:'scheduler',subtitle:"Cada réplica planifica sus propias iteraciones"});populate(sched,'scheduler');const kv=add(c,'kv',"Gestión de bloques KV",.035,.61,.205,.28,{kind:'cache',topic:'kvpages',subtitle:"Vista lógica de la HBM de cada rango"});populate(kv,'kv');const routing=add(c,'router',"Enrutador de célula",.38,.055,.34,.10,{kind:'service',topic:'router',subtitle:"Coste de cola + prefijo reutilizable"});edge(routing,sched,'request',"Admitir en una réplica lista",c);edge(kv,sched,'control',"Bloques libres / índice de prefijos",c);
 const machines=[];for(let i=0;i<6;i++){const role=i<2?'Prefill':'Decode';const machine=add(c,'node-'+i,'Nodo de '+(role==='Prefill'?'prellenado':'decodificación')+' '+(i<2?i:i-2),.305+(i%3)*.225,.225+Math.floor(i/3)*.385,.196,.285,{kind:'node',topic:'cpu',subtitle:"8 GPU · una réplica del modelo",role,zoneId:zone.id});populate(machine,'node');machines.push(machine);edge(sched,machine,'control',"Despacho de iteraciones",c);}
 edge(machines[0],machines[2],'kv',"Transferencia del K/V de entrada",c);edge(machines[1],machines[3],'kv',"Transferencia del K/V de entrada",c);edge(machines[0],machines[4],'kv',"Transferencia del K/V de entrada",c);edge(machines[1],machines[5],'kv',"Transferencia del K/V de entrada",c);edge(kv,machines[2],'control',"Mapeos lógicos; los tensores permanecen en HBM",c);clusterRefs.push({zone,c,sched,kv,routing,machines});return c;}
for(const [id,title,x,y] of [['zone-a',"Zona A",.025,.07],['zone-b',"Zona B",.51,.07],['zone-c',"Zona C",.27,.535]]){const zone=add(region,id,title,x,y,.455,.415,{kind:'zone',topic:'cell_b',subtitle:"Límite de fallo de infraestructura"});const c=cluster(zone,"Célula de inferencia "+title.slice(-1),'cell');edge(router,c,'request',"Enrutar hacia capacidad lista",root);}
const recovery=add(standby,'ready',"Preparación para recuperación",.09,.16,.82,.34,{kind:'cluster',topic:'fleet-regions',subtitle:"Modelos, políticas, datos y red preparados"});service(recovery,'compute',"Capacidad preparada",.08,.25,.38,.26,'fleet-autoscale');service(recovery,'artifacts',"Artefactos compatibles",.55,.25,.38,.26,'models');service(recovery,'data',"Replicación de datos",.08,.64,.38,.24,'database');service(recovery,'routing',"Activación de tráfico",.55,.64,.38,.24,'fleet-regions');
const streamState=add(standby,'stream',"Flujos interrumpidos",.09,.59,.82,.24,{kind:'service',topic:'client',subtitle:"El reenrutamiento no recrea el KV perdido"});
root.copy=notes("Flota en la nube","Un sistema de inferencia es una constelación de dominios de fallo. Acércate a una célula y entra en un planificador, una caché o un nodo GPU.","Los mismos objetos mantienen sus coordenadas mientras se mueve la cámara. Esta referencia tiene tres zonas, cada una con dos réplicas de prellenado y cuatro de decodificación. Cada réplica ilustrada usa ocho rangos GPU en un nodo. Los bloques lógicos de servicio representan servicios replicados, no servidores únicos.","Aquí el prellenado y la decodificación usan grupos de recursos separados. Una región de recuperación necesita sus propios modelos, políticas, datos y capacidad preparados; no basta con disponer de GPU libres.","Cuando falla un rango, su grupo de modelo puede perder el estado de ejecución en curso. Las réplicas listas protegen las nuevas admisiones; continuar un flujo ya visible exige un contrato explícito de recuperación.","Mide las solicitudes completadas a tiempo, el tiempo hasta el primer token, las pausas entre tokens, el trabajo desperdiciado tras cancelaciones y la capacidad por dominio de fallo.",[...topics['cell_b'].sources,...topics['router'].sources]);
const stateDefault={batch:32,context:8192,weight:2,kv:2,arrival:3,cache:0,retry:0,failure:'none',hbmEff:55,computeEff:55,tp:8,pp:1,output:256,groups:12,prefillGroups:6,prefillRate:6000,link:25,kvLink:25,fabric:100,block:16};let state={...stateDefault};
function calc(q){const s=q.context+q.output,L=80,H=8192,P=70e9,kvToken=2*L*8*128*q.kv,kvRank=kvToken/8,weights=P*q.weight/8,kv=kvRank*Math.ceil((s+1)/16)*16*q.batch,reserve=8e9,total=weights+kv+reserve,bw=3.35e12*q.hbmEff/100,f=989e12*q.computeEff/100,projection=Math.max(2*P*q.batch/8/f,weights/bw),attention=Math.max(4*L*q.batch*s*H/8/f,kvRank*q.batch*(s+1)/bw),collective=2*L*(8e-6+2*7/8*(q.batch*H*2)/200e9),step=projection+attention+collective+.0003,fit=total<=80e9,rate=fit?q.batch/step:0,live=q.failure==='zone'?8:12,liveP=q.failure==='zone'?4:6,pCap=liveP*q.prefillRate/Math.max(1,q.context*(1-q.cache/100)),dCap=live*rate/(q.output-1),fabric=q.fabric*1e9*(q.failure==='zone'?2/3:1),linkCap=fabric/(q.context*kvToken),capacity=Math.min(pCap,dCap,linkCap),demand=q.arrival*(1+q.retry/100);return {s,kvToken,kvRank,weights,kv,reserve,total,projection,attention,collective,step,fit,rate,live,liveP,pCap,dCap,linkCap,capacity,demand,util:capacity?demand/capacity:Infinity};}
let result=calc(state);
const fmt=(x,d=1)=>Number.isFinite(x)?x.toLocaleString('es-ES',{maximumFractionDigits:d,minimumFractionDigits:d}):'∞';
function topic(n){return n.copy||topics[n.topic]||notes(n.title,n.subtitle,"Este componente pertenece a "+n.parent.title+'.');}
function select(n,focus=false){if(!n)return;selected=n;const t=topic(n);$('#selection-kind').textContent=n===root?"Vista general de la flota":n.kind==='cache'?"Estado KV / vistas lógica y física":n.viewId?views[n.viewId].label:n.parent.title;$('#selection-title').textContent=n.title;$('#selection-summary').textContent=t.summary||n.subtitle;$('#detail-copy').innerHTML=[["Mecanismo",t.mechanism],["Compromiso de diseño",t.tradeoff],["Fallo y recuperación",t.failure],["Qué observar",t.observe]].filter(x=>x[1]).map(([h,c])=>`<h3>${escape(h)}</h3><p>${escape(c)}</p>`).join('');const connections=edges.filter(e=>e.parent===n||e.a===n||e.b===n);if(connections.length)$('#detail-copy').innerHTML+=`<details><summary>Conexiones de esta vista</summary>${connections.map(e=>`<p><strong>${escape(e.a.title)} → ${escape(e.b.title)}</strong><br>${escape(e.label||({request:'solicitud',control:'control',kv:'KV'}[e.type]||e.type))} · ${escape(e.type==='kv'?"Datos KV":e.type==='control'?"control / metadatos":"solicitud / activaciones")}</p>`).join('')}</details>`;$('#source-links').innerHTML=(t.sources||[]).map(s=>`<a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.title)} ↗</a>`).join('');$('#child-section').hidden=!n.children.length;$('#child-list').innerHTML=n.children.map(ch=>`<button class="child-list-item" data-node="${ch.id}"><span>${escape(ch.title)}</span><span>${ch.children.length?'↘':'·'}</span></button>`).join('');$('#child-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{select(byId.get(b.dataset.node),true);if(innerWidth<650)togglePanel(false);});$('#enter-component').textContent=n.children.length?"Explorar interior":"Centrar componente";$('#enter-component').disabled=false;const ancestry=[];let a=n;while(a){ancestry.unshift(a);a=a.parent;}$('#breadcrumbs').innerHTML=ancestry.map((a,i)=>`${i?'<span>›</span>':''}<button data-node="${a.id}">${escape(a.title)}</button>`).join('');$('#breadcrumbs').querySelectorAll('button').forEach(b=>b.onclick=()=>select(byId.get(b.dataset.node),true));renderDeepDives(n);annotateDefinitions($('#selection-summary'));annotateDefinitions($('#detail-copy'));$('#canvas-status').textContent=n.title+'. '+(n.children.length?n.children.length+(n.children.length===1?" componente anidado.":" componentes anidados."):'');if(focus)focusNode(n);requestDraw();}
function renderDeepDives(n){const related=n.id.includes('/scheduler')?['scheduler','chunked-prefill','admission','batch','sample','rank-failure']:n.id.includes('/kv')||n.id.endsWith('/hbm')?['kvpages','prefix','kv-head-replication','kv-layout','hbm','precision']:n.id.includes('/gpu-')?['hbm','sm','flash','sram','graphs','precision','speculation']:n.id.includes('/node-')?['cpu',n.role==='Prefill'?'prefill':'tp','handoff','rank-failure','pcie','nvlink','profile','health']:n.id.includes('/cell')?['prefill','handoff','tp','pp','dp','rank-failure','speculation','ep']:['fleet-quota','fleet-retries','fleet-regions','fleet-deploy','fleet-autoscale','telemetry'];const keys=Object.keys(topics);$('#deep-topic').innerHTML='<optgroup label="Temas relacionados">'+related.filter(k=>topics[k]).map(k=>`<option value="${k}">${escape(topics[k].title)}</option>`).join('')+'</optgroup><optgroup label="Todos los temas de arquitectura">'+keys.filter(k=>!related.includes(k)).map(k=>`<option value="${k}">${escape(topics[k].title)}</option>`).join('')+'</optgroup>';const render=()=>{const t=topics[$('#deep-topic').value];$('#deep-content').innerHTML=`<h3>${escape(t.title)}</h3><p>${escape(t.summary)}</p>`+[["Mecanismo",t.mechanism],["Compromiso de diseño",t.tradeoff],["Fallo / recuperación",t.failure],["Qué observar",t.observe]].filter(a=>a[1]).map(([a,b])=>`<h3>${escape(a)}</h3><p>${escape(b)}</p>`).join('')+(t.sources||[]).map(s=>`<p><a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.title)} ↗</a></p>`).join('');annotateDefinitions($('#deep-content'));};$('#deep-topic').onchange=render;render();}
let activeTab='detail';const panelScroll={detail:0,lab:0,glossary:0};
function setTab(tab){panelScroll[activeTab]=$('#inspector').scrollTop;activeTab=tab;for(const name of ['detail','lab','glossary']){$('#'+name+'-tab').setAttribute('aria-selected',String(name===tab));$('#'+name+'-tab').tabIndex=name===tab?0:-1;$('#'+name+'-panel').hidden=name!==tab;}$('#inspector').scrollTop=panelScroll[tab]||0;}
const glossaryEntries=(window.ATLAS_GLOSSARY||[]).slice().sort((a,b)=>a.term.localeCompare(b.term,'es',{numeric:true,sensitivity:'base'}));
const normalizeSpelling=s=>String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,' ').trim();
const normalizeTerm=s=>normalizeSpelling(s).toLowerCase();
const aliasEntries=new Map();for(const entry of glossaryEntries){for(const alias of [entry.term,...(entry.aliases||[])])if(alias.length>1&&(/[A-Z]/.test(alias)||/^p(?:95|99)$/.test(alias)))aliasEntries.set(alias,entry);}
const escapeRegex=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const termPattern=aliasEntries.size?new RegExp('\\b('+[...aliasEntries.keys()].sort((a,b)=>b.length-a.length).map(escapeRegex).join('|')+')\\b','g'):null;
function openGlossary(term=''){togglePanel(true);$('#glossary-search').value=term;renderGlossary();setTab('glossary');$('#inspector').scrollTop=0;$('#glossary-search').focus({preventScroll:true});}
function annotateDefinitions(container){if(!container||!termPattern)return;const existing=new Set([...container.querySelectorAll('[data-glossary-term]')].map(b=>b.dataset.glossaryTerm));const walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT,{acceptNode(node){return node.parentElement.closest('button,a,code,script,style,h2,h3,label,select,summary')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT;}});const texts=[];while(walker.nextNode())texts.push(walker.currentNode);for(const node of texts){const text=node.nodeValue;termPattern.lastIndex=0;const fragment=document.createDocumentFragment();let last=0,changed=false;for(const match of text.matchAll(termPattern)){const entry=aliasEntries.get(match[1]);if(existing.has(entry.term))continue;fragment.append(document.createTextNode(text.slice(last,match.index)));const button=document.createElement('button');button.type='button';button.className='term-link';button.dataset.glossaryTerm=entry.term;button.textContent=match[1];button.setAttribute('aria-label',"Definir "+match[1]+': '+entry.expansion);button.onclick=()=>openGlossary(entry.term);fragment.append(button);existing.add(entry.term);last=match.index+match[0].length;changed=true;}if(changed){fragment.append(document.createTextNode(text.slice(last)));node.replaceWith(fragment);}}}
function glossaryDestination(entry){const cell=clusterRefs[0],node=cell.machines[2],gpu=byId.get(node.id+'/gpus/gpu-0');const exact={GPU:gpu.id,CPU:node.id+'/cpu',CUDA:node.id+'/cpu','CUDA Graph':node.id+'/cpu/launch',RAM:node.id+'/dram',DRAM:node.id+'/dram',NIC:node.id+'/nic',RDMA:node.id+'/nic',PCIe:node.id+'/pcie',NUMA:node.id+'/pcie',NVSwitch:node.id+'/nvswitch',NVLink:node.id+'/nvswitch',SM:gpu.id+'/sms',SRAM:gpu.id+'/sms/shared',L1:gpu.id+'/sms/shared',L2:gpu.id+'/l2','Tensor Core':gpu.id+'/sms/tensor',DMA:gpu.id+'/copy'};const exactTerm=[entry.term,...(entry.aliases||[])].find(term=>exact[term]);if(exactTerm)return byId.get(exact[exactTerm]);const groups=[[['kvpages','prefix','kv-head-replication','kv-layout'],cell.kv],[['scheduler','chunked-prefill','batch','sample'],cell.sched],[['tp','pp','dp','rank-failure','cpu','ram','pcie','nic','nvlink','profile','health'],cell.machines[2]],[['prefill','handoff'],cell.machines[0]],[['hbm','precision'],byId.get(gpu.id+'/hbm')],[['sm','sram','l2','flash','graphs'],gpu],[['speculation','ep'],cell.c]];for(const [keys,node] of groups)if(keys.includes(entry.topic))return node;return nodes.find(n=>n.topic===entry.topic)||root;}
function glossaryMatchRank(entry,query){
 const spelling=normalizeSpelling(query),q=spelling.toLowerCase();if(!q)return 0;
 const names=[entry.term,entry.expansion,...(entry.aliases||[])].map(normalizeSpelling),folded=names.map(name=>name.toLowerCase()),compact=q.replace(/ /g,''),parts=q.split(' ');
 // Exact spellings preserve meaningful unit case: GB/s is bytes, Gb/s is bits.
 if(names.includes(spelling))return 0;
 if(folded.includes(q))return 1;
 if(folded.some(name=>name.replace(/ /g,'')===compact))return 2;
 if(folded.some(name=>name.startsWith(q)||name.replace(/ /g,'').startsWith(compact)))return 3;
 if(folded.some(name=>parts.every(part=>name.includes(part))))return 4;
 const text=normalizeTerm([entry.term,entry.expansion,...(entry.aliases||[]),entry.category,entry.definition,entry.context].join(' '));
 return parts.every(part=>part.length===1?text.split(' ').includes(part):text.includes(part))?5:Infinity;
}
function renderGlossary(){const query=$('#glossary-search').value,q=normalizeTerm(query);const matches=glossaryEntries.map(entry=>({entry,rank:glossaryMatchRank(entry,query)})).filter(match=>Number.isFinite(match.rank)).sort((a,b)=>a.rank-b.rank).map(match=>match.entry);$('#glossary-count').textContent=q?matches.length+" de "+glossaryEntries.length+" términos":glossaryEntries.length+" términos · orden alfabético";$('#glossary-results').innerHTML=matches.length?matches.map(e=>`<article class="glossary-entry"><h3>${escape(e.term)}</h3><p class="glossary-expansion">${escape(e.expansion)}</p><div class="glossary-category">${escape(e.category)}</div><p>${escape(e.definition)}</p><p class="glossary-context">${escape(e.context)}</p><button type="button" data-glossary-topic="${escape(e.term)}">Explorar en la arquitectura ↗</button></article>`).join(''):'<p class="glossary-empty">No hay términos coincidentes. Prueba una sigla, su nombre completo o un concepto como memoria o latencia.</p>';$('#glossary-results').querySelectorAll('[data-glossary-topic]').forEach(button=>button.onclick=()=>{const entry=glossaryEntries.find(e=>e.term===button.dataset.glossaryTopic);select(glossaryDestination(entry),true);setTab('detail');$('#deep-dives').open=true;$('#deep-topic').value=entry.topic;$('#deep-topic').dispatchEvent(new Event('change'));$('#deep-topic').focus({preventScroll:true});$('#deep-dives').scrollIntoView({block:'start'});});}
function togglePanel(show){document.body.classList.toggle('panel-closed',!show);$('#panel-toggle').setAttribute('aria-expanded',String(show));}
function screen(n){return {x:(n.x-cam.x)*cam.s+W/2,y:(n.y-cam.y)*cam.s+H/2,w:n.w*cam.s,h:n.h*cam.s};}
function world(x,y){return {x:(x-W/2)/cam.s+cam.x,y:(y-H/2)/cam.s+cam.y};}
function fit(n){const left=28,right=28,top=n===root?135:100,bottom=n===root?125:85;const s=Math.min((W-left-right)/n.w,(H-top-bottom)/n.h)*.89;return {x:n.x+n.w/2,y:n.y+n.h/2+(bottom-top)/(2*s),s};}
function focusNode(n){const target=fit(n);if(reduced){cam=target;requestDraw();return;}animation={from:{...cam},to:target,start:performance.now(),duration:650};requestDraw();}
function zoomAt(f,x=W/2,y=H/2){animation=null;const a=world(x,y),s=Math.max(baseScale*.45,Math.min(1200,cam.s*f));cam.x=a.x-(x-W/2)/s;cam.y=a.y-(y-H/2)/s;cam.s=s;requestDraw();}
function requestDraw(){if(!drawQueued){drawQueued=true;requestAnimationFrame(draw);}}
function rect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,Math.min(r,w/3,h/3));}
function cloudPath(n){const {x,y,w,h}=n;ctx.beginPath();ctx.moveTo(x+.13*w,y+.12*h);ctx.bezierCurveTo(x+.09*w,y-.005*h,x+.3*w,y-.025*h,x+.39*w,y+.05*h);ctx.bezierCurveTo(x+.48*w,y-.05*h,x+.68*w,y-.02*h,x+.73*w,y+.055*h);ctx.bezierCurveTo(x+.91*w,y+.015*h,x+1.015*w,y+.2*h,x+.985*w,y+.35*h);ctx.bezierCurveTo(x+1.04*w,y+.51*h,x+1.02*w,y+.81*h,x+.94*w,y+.88*h);ctx.bezierCurveTo(x+.87*w,y+1.015*h,x+.65*w,y+1.025*h,x+.52*w,y+.96*h);ctx.bezierCurveTo(x+.34*w,y+1.045*h,x+.13*w,y+.995*h,x+.10*w,y+.9*h);ctx.bezierCurveTo(x-.015*w,y+.85*h,x-.035*w,y+.61*h,x+.015*w,y+.48*h);ctx.bezierCurveTo(x-.02*w,y+.24*h,x+.025*w,y+.14*h,x+.13*w,y+.12*h);ctx.closePath();}
function visible(n){const s=screen(n);return s.x+s.w>-60&&s.y+s.h>-60&&s.x<W+60&&s.y<H+60&&s.w>1.8&&s.h>1.8;}
function color(n){if(state.failure==='zone'&&n.id.includes('/zone-a'))return palette.failed;return palette[n.kind]||palette.service;}
function alpha(hex,a){return hex+Math.round(Math.max(0,Math.min(1,a))*255).toString(16).padStart(2,'0');}
function wrap(text,maxWidth,size,maxLines=2){const words=text.split(' '),lines=[];let current='';ctx.font=`500 ${size}px "DM Sans", sans-serif`;for(const word of words){const test=current?current+' '+word:word;if(ctx.measureText(test).width>maxWidth&&current){lines.push(current);current=word;if(lines.length===maxLines)break;}else current=test;}if(lines.length<maxLines&&current)lines.push(current);if(lines.length&&ctx.measureText(lines[lines.length-1]).width>maxWidth){let l=lines[lines.length-1];while(l.length>1&&ctx.measureText(l+'…').width>maxWidth)l=l.slice(0,-1);lines[lines.length-1]=l+'…';}return lines;}
function drawNode(n,labelsOnly=false){if(n===root||!visible(n))return;const s=screen(n),c=color(n),selectedNow=n===selected,hover=n===hovered,group=n.children.length>0;ctx.save();const opacity=n.parent===root?1:Math.min(1,Math.max(.10,(Math.min(s.w,s.h)-3)/30));ctx.globalAlpha=opacity;
 if(!labelsOnly){if(['cloud','zone'].includes(n.kind))cloudPath(n);else rect(n.x,n.y,n.w,n.h,group?n.w*.035:n.w*.07);
 const fill=n.kind==='cloud'?'#0c2a3e':n.kind==='zone'?'#102f43':n.kind==='cluster'?'#0a2638':n.kind==='node'?'#123a45':n.kind==='gpu'?'#174151':n.kind==='cache'?'#3c352c':n.kind==='scheduler'?'#2d354c':'#163447';ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=alpha(c,selectedNow?1:hover?.95:group?.64:.48);ctx.lineWidth=(selectedNow?2.6:hover?2:1)/cam.s;if(n.kind==='zone')ctx.setLineDash([7/cam.s,5/cam.s]);ctx.stroke();ctx.setLineDash([]);ctx.restore();return;}
 if(n.kind==='zone'&&s.w<340){ctx.restore();return;}
 if(s.w<65||s.h<28){if(s.w>8&&s.h>8){ctx.fillStyle=alpha(c,.55);ctx.beginPath();ctx.arc(n.x+n.w/2,n.y+n.h/2,Math.min(2.2,s.w*.08)/cam.s,0,Math.PI*2);ctx.fill();}ctx.restore();return;}
 if(n.kind==='page'){ctx.fillStyle=n.shared?'#ceb376':'#6da1b5';rect(n.x+n.w*.12,n.y+n.h*.34,n.w*.76,n.h*.3,2/cam.s);ctx.fill();}
 const labelSize=Math.max(12,Math.min(group?19:16,s.w*.064));const pad=Math.max(7,Math.min(20,s.w*.045))/cam.s;const textW=n.w-2*pad;const f=labelSize/cam.s;
 ctx.fillStyle='#dfedf4';ctx.textBaseline='top';ctx.textAlign='left';const above=n.parent===root&&s.w<145;const lines=wrap(n.title,textW,f,above?2:group?1:2);const yy=above?n.y-lines.length*f*1.2-6/cam.s:group?n.y+pad:n.y+(n.h-lines.length*f*1.22)/2;for(let i=0;i<lines.length;i++)ctx.fillText(lines[i],n.x+pad,yy+i*f*1.22);
 if(group&&s.w>240&&s.h>170&&n.subtitle&&(!['cloud','zone'].includes(n.kind)||s.w>1100)){const sub=12/cam.s;ctx.font=`400 ${sub}px "DM Sans", sans-serif`;ctx.fillStyle='#97b9ca';let txt=n.subtitle;if(n.kind==='node'&&result&&!result.fit)txt="Esta carga supera el presupuesto de HBM";if(n.id.endsWith('/hbm'))txt=fmt(result.total/1e9)+" / 80 GB por rango";if(state.failure==='zone'&&n.kind==='zone'&&n.id.includes('zone-a'))txt="No disponible · hay que desviar el tráfico nuevo";while(ctx.measureText(txt).width>textW&&txt.length>4)txt=txt.slice(0,-2);ctx.fillText(txt,n.x+pad,n.y+pad+f*1.4);}
 if(n.kind==='cache'&&n.id.endsWith('/hbm')&&s.w>85){const inner=n.w*.8;let x=n.x+n.w*.1;const y=n.y+n.h*.94;for(const [v,col] of [[result.weights,'#6dc7dd'],[result.kv,'#dcb574'],[result.reserve,'#b5a7df']]){ctx.fillStyle=col;ctx.fillRect(x,y,inner*v/Math.max(80e9,result.total),n.h*.025);x+=inner*v/Math.max(80e9,result.total);}}
 ctx.restore();}
function endpoints(e){const a=e.a,b=e.b,ac={x:a.x+a.w/2,y:a.y+a.h/2},bc={x:b.x+b.w/2,y:b.y+b.h/2};const dx=bc.x-ac.x,dy=bc.y-ac.y;function boundary(n,sign){const t=1/Math.max(Math.abs(dx)/(n.w/2),Math.abs(dy)/(n.h/2));return {x:n.x+n.w/2+sign*dx*t,y:n.y+n.h/2+sign*dy*t};}return {a:boundary(a,1),b:boundary(b,-1)};}
function drawEdge(e,labels){const parentScreen=screen(e.parent),rootEdge=e.parent===root;if(!rootEdge&&parentScreen.w<390)return;if(!rootEdge&&!visible(e.parent))return;const ps=endpoints(e);const ax=(ps.a.x-cam.x)*cam.s+W/2,ay=(ps.a.y-cam.y)*cam.s+H/2,bx=(ps.b.x-cam.x)*cam.s+W/2,by=(ps.b.y-cam.y)*cam.s+H/2;if(Math.max(ax,bx)<0||Math.min(ax,bx)>W||Math.max(ay,by)<0||Math.min(ay,by)>H)return;ctx.save();const c=palette[e.type],detail=Math.min(1,Math.max(.1,(parentScreen.w-350)/400));ctx.strokeStyle=alpha(c,rootEdge?.50:.65*detail);ctx.lineWidth=(rootEdge?1.5:1.3)/cam.s;ctx.setLineDash(e.type==='kv'?[6/cam.s,4/cam.s]:e.type==='control'?[2/cam.s,5/cam.s]:[]);const dx=ps.b.x-ps.a.x,dy=ps.b.y-ps.a.y;ctx.beginPath();ctx.moveTo(ps.a.x,ps.a.y);if(Math.abs(dx)>Math.abs(dy))ctx.bezierCurveTo(ps.a.x+dx*.5,ps.a.y,ps.a.x+dx*.5,ps.b.y,ps.b.x,ps.b.y);else ctx.bezierCurveTo(ps.a.x,ps.a.y+dy*.5,ps.b.x,ps.a.y+dy*.5,ps.b.x,ps.b.y);ctx.stroke();ctx.setLineDash([]);const angle=Math.atan2(dy,dx),r=5/cam.s;ctx.beginPath();ctx.moveTo(ps.b.x,ps.b.y);ctx.lineTo(ps.b.x-Math.cos(angle-.45)*r,ps.b.y-Math.sin(angle-.45)*r);ctx.lineTo(ps.b.x-Math.cos(angle+.45)*r,ps.b.y-Math.sin(angle+.45)*r);ctx.closePath();ctx.fillStyle=alpha(c,.7);ctx.fill();
 if((e.a===hovered||e.b===hovered)&&parentScreen.w>520&&e.label&&Math.hypot(bx-ax,by-ay)>160){labels.push({text:e.label,x:(ps.a.x+ps.b.x)/2,y:(ps.a.y+ps.b.y)/2,color:c});}
 ctx.restore();}
function drawEdgeLabel(label){ctx.save();ctx.font=`400 ${11/cam.s}px "DM Sans", sans-serif`;const tw=ctx.measureText(label.text).width;ctx.fillStyle='#092333';ctx.fillRect(label.x-tw/2-4/cam.s,label.y-7/cam.s,tw+8/cam.s,15/cam.s);ctx.fillStyle=alpha(label.color,.95);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label.text,label.x,label.y);ctx.restore();}
function draw(){drawQueued=false;const edgeLabels=[];if(animation){const t=Math.min(1,(performance.now()-animation.start)/animation.duration),e=1-Math.pow(1-t,3);cam={x:animation.from.x+(animation.to.x-animation.from.x)*e,y:animation.from.y+(animation.to.y-animation.from.y)*e,s:Math.exp(Math.log(animation.from.s)+(Math.log(animation.to.s)-Math.log(animation.from.s))*e)};if(t>=1)animation=null;}
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);ctx.fillStyle='#092333';ctx.fillRect(0,0,W,H);ctx.fillStyle='#42607866';const grid=44,ox=((W/2-cam.x*cam.s)%grid+grid)%grid,oy=((H/2-cam.y*cam.s)%grid+grid)%grid;for(let x=ox;x<W;x+=grid)for(let y=oy;y<H;y+=grid)ctx.fillRect(x,y,1,1);
 ctx.setTransform(dpr*cam.s,0,0,dpr*cam.s,dpr*(W/2-cam.x*cam.s),dpr*(H/2-cam.y*cam.s));
 // All objects keep their world coordinates. Only the camera and label visibility change.
 for(let depth=1;depth<=12;depth++){for(const n of nodes)if(n.depth===depth)drawNode(n);for(const e of edges)if(e.parent.depth===depth-1)drawEdge(e,edgeLabels);}
 for(const n of nodes)drawNode(n,true);
 if(selected&&selected!==root){ctx.save();const n=selected;ctx.strokeStyle='#d7f3ff';ctx.lineWidth=1.5/cam.s;ctx.setLineDash([3/cam.s,5/cam.s]);rect(n.x-5/cam.s,n.y-5/cam.s,n.w+10/cam.s,n.h+10/cam.s,n.w*.04);ctx.stroke();ctx.restore();}
 // Connection annotations must stay above node bodies, titles and selection outlines.
 for(const label of edgeLabels)drawEdgeLabel(label);
 $('#scale').value=fmt(cam.s/baseScale,cam.s/baseScale>100?0:1)+'×';drawMinimap();canvas.dataset.cameraScale=cam.s;canvas.dataset.selected=selected?.id||'fleet';if(animation)requestDraw();}
function drawMinimap(){const sw=184,sh=116,s=Math.min((sw-12)/root.w,(sh-12)/root.h),ox=(sw-root.w*s)/2,oy=(sh-root.h*s)/2;mctx.clearRect(0,0,sw,sh);mctx.fillStyle='#082030';mctx.fillRect(0,0,sw,sh);for(const n of nodes){if(n.depth>3)continue;mctx.strokeStyle=alpha(color(n),.55);mctx.lineWidth=.7;mctx.strokeRect(ox+n.x*s,oy+n.y*s,n.w*s,n.h*s);}mctx.strokeStyle='#d4f4ff';mctx.fillStyle='#8bdcf01c';const x=ox+(cam.x-W/(2*cam.s))*s,y=oy+(cam.y-H/(2*cam.s))*s,w=W/cam.s*s,h=H/cam.s*s;mctx.fillRect(x,y,w,h);mctx.strokeRect(x,y,w,h);}
function hit(x,y){const p=world(x,y);let found=root;for(const n of nodes){const s=screen(n);if(n===root||s.w<67||s.h<28||s.w>W*5||s.h>H*5)continue;if(p.x>=n.x&&p.x<=n.x+n.w&&p.y>=n.y&&p.y<=n.y+n.h&&n.depth>=found.depth)found=n;}return found;}
function resize(){const b=canvas.getBoundingClientRect(),oldW=W,oldH=H;W=b.width;H=b.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);baseScale=fit(root).s;if(oldW===1||oldH===1)cam=fit(root);requestDraw();}
new ResizeObserver(resize).observe(canvas);
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoomAt(Math.exp(-e.deltaY*(e.ctrlKey?.006:.0015)),e.clientX-r.left,e.clientY-r.top);},{passive:false});
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top};pointers.set(e.pointerId,p);canvas.setPointerCapture(e.pointerId);animation=null;if(pointers.size===1)pointer={id:e.pointerId,x:p.x,y:p.y,cx:cam.x,cy:cam.y,moved:false};if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),cx:(a.x+b.x)/2,cy:(a.y+b.y)/2};if(pointer)pointer.moved=true;}canvas.classList.add('dragging');});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top};if(pointers.has(e.pointerId))pointers.set(e.pointerId,p);if(pointers.size===2&&pinch){const[a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),cx=(a.x+b.x)/2,cy=(a.y+b.y)/2;zoomAt(distance/Math.max(1,pinch.distance),cx,cy);cam.x-=(cx-pinch.cx)/cam.s;cam.y-=(cy-pinch.cy)/cam.s;pinch={distance,cx,cy};requestDraw();return;}if(pointer&&pointer.id===e.pointerId){const dx=p.x-pointer.x,dy=p.y-pointer.y;if(Math.hypot(dx,dy)>4)pointer.moved=true;cam.x=pointer.cx-dx/cam.s;cam.y=pointer.cy-dy/cam.s;requestDraw();}else{hovered=hit(p.x,p.y);canvas.classList.toggle('hovering',hovered!==root);requestDraw();}});
canvas.addEventListener('pointerup',e=>{if(pointer&&pointer.id===e.pointerId&&!pointer.moved&&pointers.size===1){const r=canvas.getBoundingClientRect();select(hit(e.clientX-r.left,e.clientY-r.top));}pointers.delete(e.pointerId);pointer=null;pinch=null;canvas.classList.remove('dragging');});canvas.addEventListener('pointercancel',()=>{pointer=null;pinch=null;pointers.clear();canvas.classList.remove('dragging');});canvas.addEventListener('pointerleave',()=>{hovered=null;requestDraw();});
canvas.addEventListener('dblclick',e=>{const r=canvas.getBoundingClientRect(),n=hit(e.clientX-r.left,e.clientY-r.top);select(n,true);});
canvas.addEventListener('keydown',e=>{if(['+','=','-','Escape','Home','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();if(e.key==='+'||e.key==='=')zoomAt(1.4);if(e.key==='-')zoomAt(1/1.4);if(e.key==='Home')select(root,true);if(e.key==='Escape')select(selected.parent||root,true);if(e.key.startsWith('Arrow')){animation=null;cam.x+=(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)*70/cam.s;cam.y+=(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)*70/cam.s;requestDraw();}});
mini.addEventListener('click',e=>{const r=mini.getBoundingClientRect(),s=Math.min(172/root.w,104/root.h),ox=(184-root.w*s)/2,oy=(116-root.h*s)/2;animation=null;cam.x=((e.clientX-r.left)*184/r.width-ox)/s;cam.y=((e.clientY-r.top)*116/r.height-oy)/s;requestDraw();});
$('#zoom-in').onclick=()=>zoomAt(1.5);$('#zoom-out').onclick=()=>zoomAt(1/1.5);$('#overview').onclick=()=>select(root,true);$('#go-up').onclick=()=>select(selected.parent||root,true);$('#enter-component').onclick=()=>{focusNode(selected);if(innerWidth<650)togglePanel(false);};$('#panel-toggle').onclick=()=>togglePanel(document.body.classList.contains('panel-closed'));$('#detail-tab').onclick=()=>setTab('detail');$('#lab-tab').onclick=()=>setTab('lab');$('#glossary-tab').onclick=()=>{setTab('glossary');$('#glossary-search').focus({preventScroll:true});};$('#glossary-search').addEventListener('input',renderGlossary);
const inspectorTabs=[...document.querySelectorAll('.panel-tabs [role=tab]')];inspectorTabs.forEach((tab,i)=>tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(i+1)%inspectorTabs.length;else if(event.key==='ArrowLeft')next=(i+inspectorTabs.length-1)%inspectorTabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=inspectorTabs.length-1;else return;event.preventDefault();setTab(inspectorTabs[next].id.replace('-tab',''));inspectorTabs[next].focus();}));
const A=clusterRefs[0],gpu0=byId.get(A.machines[2].id+'/gpus/gpu-0'),tour=[
 [root,"La flota y sus dominios de fallo",4], [admission,"Admitir trabajo antes de saturar las colas",5], [A.zone,"Perder una zona y conservar capacidad útil",6], [A.c,"Seguir una solicitud hasta una célula de inferencia",4], [A.sched,"Dentro del planificador de iteraciones",5], [A.kv,"Secuencias lógicas → páginas KV físicas",5], [A.machines[2],"Una réplica de modelo distribuida en ocho GPU",6], [gpu0,"Pesos, KV y jerarquía de memoria de la GPU",5], [byId.get(gpu0.id+'/sms'),"Dentro del multiprocesador de flujo",6], [A.machines[0],"Prellenado / decodificación y transferencia de KV",5], [monitor,"Medir flujos completos y a tiempo",4]
];
function showTour(i){tourActive=true;tourIndex=Math.max(0,Math.min(tour.length-1,i));const[n,title,minutes]=tour[tourIndex];$('#tour-bar').hidden=false;$('#tour-progress').textContent=`${tourIndex+1} / ${tour.length} · ${minutes} min`;$('#tour-title').textContent=title;$('#tour-prev').disabled=tourIndex===0;$('#tour-next').textContent=tourIndex===tour.length-1?"Finalizar":"Siguiente parada →";setTab('detail');select(n,true);if(innerWidth<650)togglePanel(false);}
$('#tour-toggle').onclick=()=>showTour(0);$('#tour-prev').onclick=()=>showTour(tourIndex-1);$('#tour-next').onclick=()=>{if(tourIndex===tour.length-1){$('#tour-bar').hidden=true;tourActive=false;}else showTour(tourIndex+1);};$('#tour-close').onclick=()=>{$('#tour-bar').hidden=true;tourActive=false;};
const trace=[ [clients,"El cliente envía una entrada y un plazo; la transmisión es una única solicitud de larga duración."],[admission,"Aplica presupuestos por cliente y estima la demanda de entrada, salida y KV antes de aceptar trabajo."],[router,"Elige una réplica compatible y lista según el coste de su cola y la localidad de su caché."],[A.sched,"El planificador de la réplica asigna trabajo de tokens y bloques KV entre iteraciones."],[A.machines[0],"El prellenado construye el K/V de la entrada y los logits usados para el primer token de salida."],[A.kv,"Transfiere KV compatible a la réplica de decodificación. Esta vista lógica asocia tokens con páginas locales de cada rango."],[A.machines[2],"Los ocho rangos TP cooperan en el siguiente pase hacia delante; un rango lento puede retrasar todo el lote."],[byId.get(gpu0.id+'/hbm'),"Lee los pesos residentes y el K/V anterior; añade el estado del token recién consumido."],[byId.get(gpu0.id+'/sms'),"Las funciones de proyección y atención se ejecutan en los SM, usando almacenamiento en el chip y unidades tensoriales o vectoriales."],[clients,"Muestrea, transmite y repite. La cancelación debe llegar al proceso de ejecución antes de recuperar las páginas."] ];
$('#trace-next').onclick=()=>{traceIndex=(traceIndex+1)%trace.length;const[n,copy]=trace[traceIndex];select(n,true);$('#trace-note').hidden=false;$('#trace-note').textContent=`${traceIndex+1}/${trace.length} · ${copy}`;annotateDefinitions($('#trace-note'));};
const controls=[['arrival',"Tráfico entrante",.5,30,.5,"solicitudes/s"],['batch',"Lote activo de decodificación",1,128,1,"secuencias"],['context',"Contexto de entrada",512,65536,512,'tokens'],['cache',"Fracción reutilizable de la entrada",0,95,5,'%'],['retry',"Tráfico adicional por reintentos",0,100,5,'%']];
function controlsHTML(){return controls.map(([id,label,min,max,step,unit])=>`<label class="field"><span class="field-top"><span>${label}</span><output id="out-${id}">${fmt(state[id],id==='arrival'?1:0)} ${unit}</output></span><input id="param-${id}" data-param="${id}" aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${state[id]}"></label>`).join('')+`<label class="field">Precisión de los pesos<select data-param="weight"><option value="2" ${state.weight===2?'selected':''}>BF16 · 2 bytes</option><option value="1" ${state.weight===1?'selected':''}>8 bits · 1 byte</option><option value="0.5" ${state.weight===.5?'selected':''}>4 bits · 0,5 bytes</option></select></label><label class="field">Precisión de KV<select data-param="kv"><option value="2" ${state.kv===2?'selected':''}>BF16 · 2 bytes</option><option value="1" ${state.kv===1?'selected':''}>8 bits · 1 byte</option></select></label>`;}
function renderControls(){$('#lab-controls').innerHTML=controlsHTML();$('#lab-controls').querySelectorAll('[data-param]').forEach(el=>el.oninput=()=>{state[el.dataset.param]=+el.value;const c=controls.find(c=>c[0]===el.dataset.param);if(c)$('#out-'+c[0]).textContent=fmt(+el.value,c[0]==='arrival'?1:0)+' '+c[5];$('#scenario').value='baseline';updateLab();});}
function updateLab(){result=calc(state);const r=result;const note=!r.fit?"Este lote no puede ejecutarse sin reducir el uso de memoria o cambiar la ubicación de las cargas.":r.util>=1?"El trabajo entrante supera la capacidad lista; limita la admisión antes de que los reintentos y las colas agraven el fallo.":"La capacidad libre estimada no garantiza SLO de latencia en los percentiles altos ni de disponibilidad.";$('#lab-results').innerHTML=`<div class="metric"><div class="metric-label">Asignación de HBM / rango GPU</div><div class="metric-value ${!r.fit?'alert-text':''}">${fmt(r.total/1e9)} / 80 GB</div><div class="bar-track"><span style="width:${r.weights/80e9*100}%;background:#168aab"></span><span style="width:${r.kv/80e9*100}%;background:#c19143"></span><span style="width:${r.reserve/80e9*100}%;background:#a292d6"></span></div><div class="metric-note">Pesos ${fmt(r.weights/1e9)} + KV ${fmt(r.kv/1e9)} + entorno de ejecución 8 GB</div></div><div class="metric"><div class="metric-label">Iteración estimada de decodificación</div><div class="metric-value">${r.fit?fmt(r.step*1000,2)+' ms':"No cabe en memoria"}</div><div class="metric-note">${r.fit?fmt(r.rate,0)+" tokens/s en este lote activo":"Rendimiento desactivado para un lote inviable"}</div></div><div class="metric"><div class="metric-label">Trabajo entrante / capacidad restante</div><div class="metric-value ${r.util>=1?'alert-text':''}">${fmt(r.demand)} / ${fmt(r.capacity)} solicitudes/s</div><div class="metric-note">${r.live} réplicas de decodificación · ${r.live*8} GPU de decodificación · ${r.liveP} réplicas de prellenado</div></div><p class="metric-note ${r.util>=1||!r.fit?'alert-text':''}">${note}</p>`;
 $('#model-notes').innerHTML=`<p>Modelo denso GQA de 70 mil millones de parámetros: 80 capas, dimensión oculta de 8192, 8 cabezas KV y dimensión por cabeza de 128; TP8 / PP1. Cada nodo mostrado es una réplica. Es una topología esquemática, no una medición del rendimiento de un proveedor.</p><p><code>KV/token = 2 × 80 × 8 × 128 × bytes_KV</code>. Con BF16 son 320 KiB/modelo o 40 KiB/rango. La memoria reserva la entrada + 256 tokens de salida, redondeados a páginas de 16 tokens, más 8 GB/rango para el entorno de ejecución.</p><p>Suma los límites del modelo de techo de rendimiento para proyección y atención, y después la sobrecarga de las operaciones colectivas y del anfitrión. H100 SXM: 3,35 TB/s de HBM y unos 989 TFLOP/s de BF16 denso; se supone una eficiencia del 55 % en ambos casos. Enlace colectivo TP: se suponen 200 GB/s, 8 µs de inicio y dos reducciones/capa. Anfitrión: 0,3 ms.</p><p>La capacidad de la flota es el mínimo entre las capacidades de prellenado, decodificación y transferencia agregada de KV. Prellenado: se suponen 6000 tokens sin caché/s/réplica. Red de interconexión: se suponen 100 GB/s de datos únicos de entrada. El fallo de una zona elimina un tercio de la capacidad aprovisionada. El prellenado aporta el primer token; las 255 salidas restantes consumen capacidad de decodificación.</p><p>No se presentan mediciones de p99 ni de niveles de disponibilidad expresados en nueves. No se modelan la calidad de cuantización, el coste de descuantización, los lotes de longitud variable, el almacenamiento compartido de prefijos, MoE, la decodificación especulativa, la contención de red ni todo el espacio de trabajo temporal. La precisión cambia los bytes almacenados, no el cálculo tensorial supuesto. Reutilizar la caché reduce aquí el trabajo de prellenado; la decodificación sigue leyendo el historial retenido.</p><p><a href="https://www.nvidia.com/en-us/data-center/h100/" target="_blank" rel="noopener noreferrer">Especificaciones de H100</a> · <a href="https://arxiv.org/abs/2309.06180" target="_blank" rel="noopener noreferrer">PagedAttention</a></p>`;annotateDefinitions($('#lab-results'));annotateDefinitions($('#model-notes'));canvas.dataset.fit=String(r.fit);canvas.dataset.util=String(r.util);requestDraw();}
$('#scenario').onchange=e=>{const v=e.target.value;state={...stateDefault};if(v==='zone'){state.failure='zone';select(A.zone,true);}if(v==='burst'){state.arrival=8;state.retry=50;select(admission,true);}if(v==='context'){state.context=32768;state.batch=64;select(byId.get(gpu0.id+'/hbm'),true);}if(v==='quant'){state.weight=.5;state.kv=1;select(byId.get(gpu0.id+'/hbm'),true);}if(v==='baseline')select(root,true);renderControls();updateLab();};
renderGlossary();setTab('detail');if(innerWidth<650)togglePanel(false);renderControls();updateLab();select(root);resize();document.fonts.ready.then(requestDraw);
// Stable, read-only metadata makes geometry invariants inspectable during QA.
window.constellation={getNode:id=>{const n=byId.get(id);return n?{id:n.id,x:n.x,y:n.y,w:n.w,h:n.h,parent:n.parent?.id,children:n.children.map(c=>c.id)}:null;},getCamera:()=>({...cam}),nodeCount:nodes.length,edgeCount:edges.length};
})();
